#define SHIM_ALL 1

#if SHIM_ALL
#warning "Shimming"
#define BDE_USE_ORIGINAL_BUFFERMANAGER 0
#define BDE_USE_ORIGINAL_CONCURRENTPOOL 0
#define BDE_USE_ORIGINAL_POOL 0
#define BDE_USE_ORIGINAL_MULTIPOOL 0
#else
#warning "Original"
#define BDE_USE_ORIGINAL_BUFFERMANAGER 1
#define BDE_USE_ORIGINAL_CONCURRENTPOOL 1
#define BDE_USE_ORIGINAL_POOL 1
#define BDE_USE_ORIGINAL_MULTIPOOL 1
#endif

#if 0
// Artifacts, left over for compatibility.

#define BDE_USE_ORIGINAL_SIMPLEPOOL 1
#define BDE_USE_ORIGINAL_BUFFERALLOCATOR 1
#define BDE_USE_ORIGINAL_BUFFEREDSEQUENTIALALLOCATOR 1
#define BDE_USE_ORIGINAL_SEQUENTIALALLOCATOR 1
#endif
